### ISSUE TITLE
MintomicTests failing to compile for ARMv7-a

### ISSUE THREAD

**Issue by tycho** [mintomic/mintomic#2]
Linux on ARM Cortex-A15, gcc 4.7.3, binutils 2.23.2.

```
[ 15%] Building C object mintomic/CMakeFiles/Mintomic.dir/mintomic_gcc.c.o
/tmp/ccJBwcxg.s: Assembler messages:
/tmp/ccJBwcxg.s:24: Error: junk at end of line, first unrecognised character is `_'
/tmp/ccJBwcxg.s:37: Error: junk at end of line, first unrecognised character is `_'
/tmp/ccJBwcxg.s:54: Error: junk at end of line, first unrecognised character is `_'
/tmp/ccJBwcxg.s:77: Error: junk at end of line, first unrecognised character is `_'
/tmp/ccJBwcxg.s:95: Error: junk at end of line, first unrecognised character is `_'
/tmp/ccJBwcxg.s:113: Error: junk at end of line, first unrecognised character is `_'
```

Doing this corrects it:
```diff
diff --git a/src/mintomic/mintomic_gcc.c b/src/mintomic/mintomic_gcc.c
index 7f9afa0..3f55431 100644
--- a/src/mintomic/mintomic_gcc.c
+++ b/src/mintomic/mintomic_gcc.c
@@ -12,12 +12,12 @@
 
 __asm__(
 "   .align 2\n"
-"   .globl _mint_thread_fence_acquire\n"
-"   .globl _mint_thread_fence_release\n"
-"   .globl _mint_thread_fence_seq_cst\n"
-"_mint_thread_fence_acquire:\n"
-"_mint_thread_fence_release:\n"
-"_mint_thread_fence_seq_cst:\n"
+"   .globl mint_thread_fence_acquire\n"
+"   .globl mint_thread_fence_release\n"
+"   .globl mint_thread_fence_seq_cst\n"
+"mint_thread_fence_acquire:\n"
+"mint_thread_fence_release:\n"
+"mint_thread_fence_seq_cst:\n"
 // Do we really need to set the source register to 0?
 "   mov r0, #0\n"
 "   mcr p15, 0, r0, c7, c10, 5\n"
@@ -26,8 +26,8 @@ __asm__(
 
 __asm__(
 "   .align  2\n"
-"   .globl  _mint_compare_exchange_strong_32_relaxed\n"
-"_mint_compare_exchange_strong_32_relaxed:\n"
+"   .globl  mint_compare_exchange_strong_32_relaxed\n"
+"mint_compare_exchange_strong_32_relaxed:\n"
 "   push    {r4}\n"
 "   mov     r4, r0\n"
 "1:\n"
@@ -44,8 +44,8 @@ __asm__(
 
 __asm__(
 "   .align  2\n"
-"   .globl  _mint_fetch_add_32_relaxed\n"
-"_mint_fetch_add_32_relaxed:\n"
+"   .globl  mint_fetch_add_32_relaxed\n"
+"mint_fetch_add_32_relaxed:\n"
 "   push    {r4}\n"
 "   mov     r4, r0\n"
 "1:\n"
@@ -60,8 +60,8 @@ __asm__(
 
 __asm__(
 "   .align  2\n"
-"   .globl  _mint_fetch_and_32_relaxed\n"
-"_mint_fetch_and_32_relaxed:\n"
+"   .globl  mint_fetch_and_32_relaxed\n"
+"mint_fetch_and_32_relaxed:\n"
 "   push    {r4}\n"
 "   mov     r4, r0\n"
 "1:\n"
@@ -76,8 +76,8 @@ __asm__(
 
 __asm__(
 "   .align  2\n"
-"   .globl  _mint_fetch_or_32_relaxed\n"
-"_mint_fetch_or_32_relaxed:\n"
+"   .globl  mint_fetch_or_32_relaxed\n"
+"mint_fetch_or_32_relaxed:\n"
 "   push    {r4}\n"
 "   mov     r4, r0\n"
 "1:\n"
@@ -131,12 +131,12 @@ __asm__(
 
 __asm__(
 "   .align  2\n"
-"   .globl  _mint_load_64_relaxed\n"
+"   .globl  mint_load_64_relaxed\n"
 #if MINT_CPU_ARM_THUMB && (MINT_CPU_ARM_VERSION != 6)
 "   .thumb\n"
-"   .thumb_func _mint_load_64_relaxed\n"
+"   .thumb_func mint_load_64_relaxed\n"
 #endif
-"_mint_load_64_relaxed:\n"
+"mint_load_64_relaxed:\n"
 "   mov     r2, r0\n"
 "1:\n"
 "   ldrexd  r0, r1, [r2]\n"
@@ -148,12 +148,12 @@ __asm__(
 
 __asm__(
 "   .align  2\n"
-"   .globl  _mint_store_64_relaxed\n"
+"   .globl  mint_store_64_relaxed\n"
 #if MINT_CPU_ARM_THUMB && (MINT_CPU_ARM_VERSION != 6)
 "   .thumb\n"
-"   .thumb_func _mint_store_64_relaxed\n"
+"   .thumb_func mint_store_64_relaxed\n"
 #endif
-"_mint_store_64_relaxed:\n"
+"mint_store_64_relaxed:\n"
 "   push    {r4-r5}\n"
 "   mov     r5, r0\n"
 "   mov     r3, r2\n"
@@ -169,12 +169,12 @@ __asm__(
 
 __asm__(
 "   .align  2\n"
-"   .globl  _mint_compare_exchange_strong_64_relaxed\n"
+"   .globl  mint_compare_exchange_strong_64_relaxed\n"
 #if MINT_CPU_ARM_THUMB && (MINT_CPU_ARM_VERSION != 6)
 "   .thumb\n"
-"   .thumb_func _mint_compare_exchange_strong_64_relaxed\n"
+"   .thumb_func mint_compare_exchange_strong_64_relaxed\n"
 #endif
-"_mint_compare_exchange_strong_64_relaxed:\n"
+"mint_compare_exchange_strong_64_relaxed:\n"
 "   push    {r4-r7}\n"
 "   mov     r6, r3\n"
 "   ldr     r7, [sp, #16]\n"
@@ -198,12 +198,12 @@ __asm__(
 
 __asm__(
 "   .align  2\n"
-"   .globl  _mint_fetch_add_64_relaxed\n"
+"   .globl  mint_fetch_add_64_relaxed\n"
 #if MINT_CPU_ARM_THUMB && (MINT_CPU_ARM_VERSION != 6)
 "   .thumb\n"
-"   .thumb_func _mint_fetch_add_64_relaxed\n"
+"   .thumb_func mint_fetch_add_64_relaxed\n"
 #endif
-"_mint_fetch_add_64_relaxed:\n"
+"mint_fetch_add_64_relaxed:\n"
 "   push    {r4-r7}\n"
 "   mov     r5, r0\n"
 "   mov     r4, r1\n"
@@ -220,12 +220,12 @@ __asm__(
 
 __asm__(
 "   .align  2\n"
-"   .globl  _mint_fetch_and_64_relaxed\n"
+"   .globl  mint_fetch_and_64_relaxed\n"
 #if MINT_CPU_ARM_THUMB && (MINT_CPU_ARM_VERSION != 6)
 "   .thumb\n"
-"   .thumb_func _mint_fetch_and_64_relaxed\n"
+"   .thumb_func mint_fetch_and_64_relaxed\n"
 #endif
-"_mint_fetch_and_64_relaxed:\n"
+"mint_fetch_and_64_relaxed:\n"
 "   push    {r4-r7}\n"
 "   mov     r5, r0\n"
 "   mov     r4, r1\n"
@@ -242,12 +242,12 @@ __asm__(
 
 __asm__(
 "   .align  2\n"
-"   .globl  _mint_fetch_or_64_relaxed\n"
+"   .globl  mint_fetch_or_64_relaxed\n"
 #if MINT_CPU_ARM_THUMB && (MINT_CPU_ARM_VERSION != 6)
 "   .thumb\n"
-"   .thumb_func _mint_fetch_or_64_relaxed\n"
+"   .thumb_func mint_fetch_or_64_relaxed\n"
 #endif
-"_mint_fetch_or_64_relaxed:\n"
+"mint_fetch_or_64_relaxed:\n"
 "   push    {r4-r7}\n"
 "   mov     r5, r0\n"
 "   mov     r4, r1\n"
```

**Comment by tycho** [comment]
Same issue just presented itself on a NVIDIA Jetson TK1 board running Ubuntu 14.04.

**Comment by tycho** [comment]
I wrote a fix -- works for both -marm and -mthumb. Haven't tested Apple's ARM target though.

https://github.com/tycho/mintomic/commit/0a351640ae1394c945e073641c0ceda0c1814749

**Comment by tycho** [comment]
OK, so I think this and #3 are related. I believe there's an ABI difference such that it's not using the right arguments for the asm implementations of the 64-bit atomics.

I think turning them into inline functions with asm bodies would fix it...

**Comment by tycho** [comment]
Redid my changes, moving the 64-bit atomics to static inline functions in the ARM header: https://github.com/tycho/mintomic/commit/cd149197b4563118d3652ccfbe0c7d57d2a7e23c

This should fix both #2 and #3.

**Comment by preshing** [comment]
I think this patch will break ARMv6 support when compiling in Thumb mode. I'm not prepared to test it at the moment, though.

Can you paste the output of `gcc -v` and `as --version` on the platform where the original code is failing to compile?

**Comment by tycho** [comment]
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.9.2-0ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --disable-werror --enable-multilib --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Ubuntu/Linaro 4.9.2-0ubuntu1~14.04) 
snoonan@tegra-ubuntu ~
$ as --version
GNU assembler (GNU Binutils for Ubuntu) 2.24
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `arm-linux-gnueabihf'.
```

**Comment by tycho** [comment]
If I add an -march=armv6t2, linkage fails with my changes. But I don't think the __asm__-defined functions are platform-agnostic right now, as they are dependent on a particular ABI.

**Comment by tycho** [comment]
On the other hand, armv7-a is fixed by my changes:

```
[1/64] Test "test_load_store_32 x 2"... pass, 81.026 ms
[2/64] Test "test_load_store_32_fail x 2"... pass, 81.646 ms
[3/64] Test "test_load_store_64 x 2"... pass, 228.286 ms
[4/64] Test "test_load_store_64_fail x 2"... pass, 108.587 ms
[5/64] Test "test_return_values_32 x 1"... pass, 9.236 ms
[6/64] Test "test_return_values_64 x 1"... pass, 16.654 ms
[7/64] Test "test_increment_32 x 1"... pass, 480.784 ms
[8/64] Test "test_increment_32 x 2"... pass, 890.758 ms
[9/64] Test "test_increment_32 x 3"... pass, 1283.901 ms
[10/64] Test "test_increment_32 x 4"... pass, 1697.142 ms
[11/64] Test "test_increment_64 x 1"... pass, 524.051 ms
[12/64] Test "test_increment_64 x 2"... pass, 1028.326 ms
[13/64] Test "test_increment_64 x 3"... pass, 1757.443 ms
[14/64] Test "test_increment_64 x 4"... pass, 2662.542 ms
[15/64] Test "test_add_triangle_32 x 1"... pass, 476.279 ms
[16/64] Test "test_add_triangle_32 x 2"... pass, 899.001 ms
[17/64] Test "test_add_triangle_32 x 3"... pass, 1294.630 ms
[18/64] Test "test_add_triangle_32 x 4"... pass, 1705.416 ms
[19/64] Test "test_add_triangle_64 x 1"... pass, 501.550 ms
[20/64] Test "test_add_triangle_64 x 2"... pass, 1028.521 ms
[21/64] Test "test_add_triangle_64 x 3"... pass, 1714.098 ms
[22/64] Test "test_add_triangle_64 x 4"... pass, 2626.888 ms
[23/64] Test "test_bitarray_32_128 x 1"... pass, 1042.182 ms
[24/64] Test "test_bitarray_32_128 x 2"... pass, 938.146 ms
[25/64] Test "test_bitarray_32_128 x 3"... pass, 901.128 ms
[26/64] Test "test_bitarray_32_128 x 4"... pass, 880.179 ms
[27/64] Test "test_bitarray_64_128 x 1"... pass, 1296.288 ms
[28/64] Test "test_bitarray_64_128 x 2"... pass, 1125.510 ms
[29/64] Test "test_bitarray_64_128 x 3"... pass, 1129.180 ms
[30/64] Test "test_bitarray_64_128 x 4"... pass, 1176.807 ms
[31/64] Test "test_bitarray_32_32768 x 1"... pass, 1106.929 ms
[32/64] Test "test_bitarray_32_32768 x 2"... pass, 726.384 ms
[33/64] Test "test_bitarray_32_32768 x 3"... pass, 548.773 ms
[34/64] Test "test_bitarray_32_32768 x 4"... pass, 457.979 ms
[35/64] Test "test_bitarray_64_32768 x 1"... pass, 1336.887 ms
[36/64] Test "test_bitarray_64_32768 x 2"... pass, 850.278 ms
[37/64] Test "test_bitarray_64_32768 x 3"... pass, 631.011 ms
[38/64] Test "test_bitarray_64_32768 x 4"... pass, 517.302 ms
[39/64] Test "test_mutex_acq_rel_32 x 1"... pass, 398.986 ms
[40/64] Test "test_mutex_acq_rel_32 x 2"... pass, 1312.344 ms
[41/64] Test "test_mutex_acq_rel_32 x 3"... pass, 2503.841 ms
[42/64] Test "test_mutex_acq_rel_32 x 4"... pass, 3518.243 ms
[43/64] Test "test_mutex_acq_rel_32_fail x 1"... pass, 275.453 ms
[44/64] Test "test_mutex_acq_rel_32_fail x 2"... g_sharedValue=9999960 fail (allowed), 728.263 ms
[45/64] Test "test_mutex_acq_rel_32_fail x 3"... g_sharedValue=14999982 fail (allowed), 1871.612 ms
[46/64] Test "test_mutex_acq_rel_32_fail x 4"... g_sharedValue=19999799 fail (allowed), 3322.945 ms
[47/64] Test "test_mutex_acq_rel_64 x 1"... pass, 473.261 ms
[48/64] Test "test_mutex_acq_rel_64 x 2"... pass, 1418.283 ms
[49/64] Test "test_mutex_acq_rel_64 x 3"... pass, 3366.803 ms
[50/64] Test "test_mutex_acq_rel_64 x 4"... pass, 6883.753 ms
[51/64] Test "test_mutex_acq_rel_64_fail x 1"... pass, 389.868 ms
[52/64] Test "test_mutex_acq_rel_64_fail x 2"... pass, 1257.266 ms
[53/64] Test "test_mutex_acq_rel_64_fail x 3"... pass, 2614.927 ms
[54/64] Test "test_mutex_acq_rel_64_fail x 4"... pass, 4454.243 ms
[55/64] Test "test_storeload_32 x 2"... pass, 14153.500 ms
[56/64] Test "test_storeload_32_fail x 2"... fail (allowed), 120.353 ms
[57/64] Test "test_linkedlist_32 x 1"... pass, 486.812 ms
[58/64] Test "test_linkedlist_32 x 2"... pass, 826.127 ms
[59/64] Test "test_linkedlist_32 x 3"... pass, 1220.659 ms
[60/64] Test "test_linkedlist_32 x 4"... pass, 1583.521 ms
[61/64] Test "test_linkedlist_64 x 1"... pass, 569.680 ms
[62/64] Test "test_linkedlist_64 x 2"... pass, 955.181 ms
[63/64] Test "test_linkedlist_64 x 3"... pass, 1269.265 ms
[64/64] Test "test_linkedlist_64 x 4"... pass, 1607.583 ms

----- Summary: -----
Out of the tests required to pass, 53/53 passed.
Out of the tests allowed to fail, 7/11 passed.
```

**Comment by preshing** [comment]
The Linux compiler uses the ELF format, which does not put underscores in front of function names, whereas Xcode's compiler uses the Mach-O format, which does. I've submitted a fix which supports both.

The tests will still fail on your platform, due to issue #3, but at least the compile issue is fixed.

**Comment by preshing** [comment]
Yea, I agree.
Does your patch make it successfully build & link with both -marm and -mthumb?

**Comment by tycho** [comment]
The patch above compiles and links with both `-marm` and `-mthumb`, yes.

**Comment by tycho** [comment]
But obviously the tests still fail because it's not the correct ABI.

And I'm curious if the above patch still builds and links with whatever toolchain you originally used to develop the Mintomic ARM bits.

**Comment by preshing** [comment]
Just gave it a try. Apple's assembler doesn't like it (in Xcode 6.1):
~~~
<inline asm>:6:4: error: unknown directive
   .type _mint_load_64_relaxed,function
   ^
~~~

**Comment by tycho** [comment]
Is that the default Apple assembler, or did you also pass `-Wa,-q`?

**Comment by preshing** [comment]
Hi tycho, Mintomic is nearing the end of its life. I've basically moved all the atomic C code to Turf: https://github.com/preshing/turf/tree/master/turf/c

Note, though, that native ARM support is currently disabled in Turf (it falls back to C++11 atomics). I'll re-enable it after a couple of issues get sorted out. (Contributions welcome :))
